//import cypress.config
///<reference types="cypress" />
describe("Training Arcade",function(){
    beforeEach(()=>{
        cy.visit('https://tga-qa.staging.thetrainingarcade.com/admin/#!/login')
    })
    it("Login",function(){
    cy.get('.panel-title.ng-binding').contains(" Sign In").should('be.visible')
    cy.get('[placeholder="Email Address"]').type('saraswathi@elblearning.com')
    cy.get('[placeholder="Password"]').type('P@ssw0rd')
    cy.get('[type="submit"]').click()
    cy.wait(1000)
   // cy.get('.navbar-brand>.logo').should('be.visible')
    cy.get('[translate="common.back"]').click()
    cy.wait(1000)
    cy.get('[ui-sref="addGame()"]').click()
    cy.wait(1000)
    cy.get('[ng-repeat="gameType in data.gameTypes"]:nth-child(2)>[type="button"]').click()
    cy.get('[name="splash_logo_type"]').select('Upload Image')
    cy.get('[name="splash_logo_image"]').selectFile('cypress\\fixtures\\tga95-ErrorSS.png')
    cy.get('.form-group.ng-scope>.fa.fa-question-circle.btn-help.ng-scope:nth-child(2)').trigger('mouseover').should('be.visible')
    cy.get('[name="name"]').type('Regression Jeopardy Game Divya')
   // cy.wait(10000)
    cy.get('[name="time_per_question"]').scrollIntoView()
    //cy.wait(10000)
    cy.get('[name="global_timer_yesno"]').select('Yes')
    cy.get('[name="time_per_question"]').type('40')
    cy.get('[name="percent_required"]').type('40')
    cy.get('[name="learn_more_url"]').type('https://docs.cypress.io/guides/core-concepts/conditional-testing')
    cy.get('[name="learn_more_button_text"]').type('Learn more')
    cy.get('[name="popup_title"]').scrollIntoView()
    cy.get('[name="popup_title"]').type('Info Popup')
    cy.get('[name="authorization_type"]').select('No Authorization')
//    cy.get('[name="registration"]').select('Yes')
    //bold text enabling
  //  cy.get('.ql-bold:nth-child(1)').click()
    cy.get('.ql-editor.ql-blank').type('Info text')
    cy.get('[name="authorization_type"]').select('No Authorization')
    cy.get('[name="registration"]').select('Yes')
    //setting email field values as optional
    cy.get('.table.table-condensed.answer-table>*>tr:nth-child(3)>*>select').select('Optional')
    //clicking a checkbox
    cy.get('.table.table-condensed.answer-table>*>tr:nth-child(3)>*>*>*>input').click()
    cy.get('[name="show_leaderboard"').select('Yes')
    cy.get('[placeholder="Subscriber Name..."]').type('Divya')
    cy.get('[placeholder="Privacy Policy URL..."]').type('https://docs.cypress.io/guides/core-concepts/conditional-testing')
   //question part
   cy.get('[heading="Questions"]').click()
   cy.get('.panel.panel-primary.ng-scope:nth-child(1)>*>*>a').click()
   cy.get('[name="round_questions_0"]').contains('2')
   cy.get('[name="category_name_0_0"]').clear().type('Category1 Jeopardy')
  // cy.get('[name="daily_double_0_1"]')
 // cy.get('.accordion-toggle>span').contains('This is placeholder for the clue text. Please replace this with the desired clue.').click()
cy.get(':nth-child(1) > .panel-body.ng-scope > .category-tabs > .tab-content > .active > .category-group > :nth-child(2) > :nth-child(1) > .panel-heading > .panel-title > .accordion-toggle').click()
cy.get(':nth-child(1) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(1) > .panel-body > :nth-child(4) > .col-sm-12 > .form-group > .ng-pristine > [ng-show="$ctrl.ready"] > .ql-container > .ql-editor').clear().type('Clue Text')
cy.get(':nth-child(1) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(1) > .panel-body > :nth-child(5) > .col-sm-6.ng-scope > .form-group > .input-group > .form-control').clear().type('40')
cy.get('[name="answer_phrase_0_0_0"]').clear().type('What is Java')
cy.get(':nth-child(1) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(1) > .panel-body > .table-responsive > .table > .ng-isolate-scope > :nth-child(1) > :nth-child(1) > .ng-scope > .form-control').clear().type('A language')
cy.get('[name="response_correct_0_0_0"]').type('Correct feedback text')
cy.get('[name="response_incorrect_0_0_0"]').type("Incorrect answer")
cy.wait(10000)
cy.get(':nth-child(1) > .panel-body.ng-scope > .category-tabs > .tab-content > .active > .category-group > :nth-child(2) > :nth-child(2) > .panel-heading > .panel-title > .accordion-toggle > .ng-binding').scrollIntoView()
cy.get(':nth-child(1) > .panel-body.ng-scope > .category-tabs > .tab-content > .active > .category-group > :nth-child(2) > :nth-child(2) > .panel-heading > .panel-title > .accordion-toggle > .ng-binding').click()
cy.wait(1000)
cy.get(':nth-child(1) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(2) > .panel-body > :nth-child(4) > .col-sm-12 > .form-group > .ng-pristine > [ng-show="$ctrl.ready"] > .ql-container > .ql-editor').clear().type("Java Program")
cy.get('[name="answer_phrase_0_0_1"]').clear().type("Number of primitive datatypes in Java are?")
cy.get('[name="answer_0_0_1_0"]').clear().type("8")
cy.get('[name="answer_0_0_1_1"]').clear().type("6")
cy.get('[name="response_correct_0_0_1"]').clear().type("Wow you're good")
cy.get('[name="response_incorrect_0_0_1"]').clear().type("Better luck next time")
//adding  question for second category in Jeopardy 
cy.get(':nth-child(1) > .panel-body.ng-scope > .category-tabs > .nav > :nth-child(2) > .nav-link').click()
cy.get('[name="category_name_0_1"]').clear().type("Category 2 Jeopardy")
cy.get(':nth-child(1) > .panel-body.ng-scope > .category-tabs > .tab-content > .active > .category-group > :nth-child(2) > :nth-child(1) > .panel-heading > .panel-title > .accordion-toggle > .ng-binding').click()
cy.get(':nth-child(1) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(1) > .panel-body > :nth-child(4) > .col-sm-12 > .form-group > .ng-pristine > [ng-show="$ctrl.ready"] > .ql-container > .ql-editor').clear().type("Java")
cy.get('[name="answer_phrase_0_1_0"]').clear().type("Which of the following comes under OOPS Concept")
cy.get('[name="answer_0_1_0_0"]').clear().type("Inheritance")
cy.get('[name="answer_0_1_0_1"]').clear().type("Incorrect")
cy.get('[name="response_correct_0_1_0"]').clear().type("Wow , You're Good")
cy.get('[name="response_incorrect_0_1_0"]').clear().type("OOPS You're Wrong")
//adding 2nd question
cy.get(':nth-child(1) > .panel-body.ng-scope > .category-tabs > .tab-content > .active > .category-group > :nth-child(2) > :nth-child(2) > .panel-heading > .panel-title > .accordion-toggle > .ng-binding').click()
cy.wait(1000)
cy.get(':nth-child(1) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(2) > .panel-body > :nth-child(4) > .col-sm-12 > .form-group > .ng-pristine > [ng-show="$ctrl.ready"] > .ql-container > .ql-editor').clear().type("Java Program")
cy.get('[name="answer_phrase_0_1_1"]').clear().type("Number of primitive datatypes in Java are?")
cy.get('[name="answer_0_1_1_0"]').clear().type("8")
cy.get('[name="answer_0_1_1_1"]').clear().type("6")
cy.get('[name="response_correct_0_1_1"]').clear().type("Wow you're good")
cy.get('[name="response_incorrect_0_1_1"]').clear().type("Better luck next time")


cy.get('.panel-title > .toggle > .switch').click()
//clicking double jeopardy
cy.get('a').contains('Double Jeopardy!').click({force:true})
cy.get(':nth-child(2) > .panel-body.ng-scope > [ng-if="g_index < 2"] > :nth-child(2) > .form-control').select("2")
//cy.get(':nth-child(2) > .panel-body.ng-scope > [ng-if="g_index < 2"] > :nth-child(3) > .form-control').children().eq(2).should('have.attr','label','Category 2').children().eq(0).invoke('value').should('exist').then((optionText) => {
 //   cy.get(':nth-child(2) > .panel-body.ng-scope > [ng-if="g_index < 2"] > :nth-child(3) > .form-control').select(optionText)
//})
cy.get('[name="category_name_1_0"]').clear().type("Category 1 for Double Jeopardy")
cy.get(':nth-child(2) > .panel-body.ng-scope > .category-tabs > .tab-content > .active > .category-group > :nth-child(2) > :nth-child(1) > .panel-heading > .panel-title > .accordion-toggle').click()
//entering clue text
cy.get(':nth-child(2) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(1) > .panel-body > :nth-child(4) > .col-sm-12 > .form-group > .ng-pristine > [ng-show="$ctrl.ready"] > .ql-container > .ql-editor').clear().type("The question is about Mathematics")
//enter time duration second
cy.get(':nth-child(2) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(1) > .panel-body > :nth-child(5) > .col-sm-6.ng-scope > .form-group > .input-group > .form-control').clear().type("20")
//enter the question text
cy.get('[name="answer_phrase_1_0_0"]').clear().type("What is 4 * 2?")
//uncheck the randomize answers checkbox
cy.get(':nth-child(2) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(1) > .panel-body > .checkbox > .ng-binding > .ng-pristine').click()
//entering answer options and making first option as default correct
cy.get('[name="answer_1_0_0_0"]').clear().type("8")
cy.get('[name="answer_1_0_0_1"]').clear().type("10")
cy.get(':nth-child(2) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(1) > .panel-body > .text-right > .btn').click()
cy.get('[name="answer_1_0_0_2"]').type("12")   
cy.get('[name="response_correct_1_0_0"]').clear().type("The correct answer")
cy.get('[name="response_incorrect_1_0_0"]').clear().type("The Incorrect answer")
cy.get('[name="response_correct_1_0_0"]').type("Good, the answer is correct")
cy.get('[name="response_incorrect_1_0_0"]').type("Oops You're wrong")
//second placeholder 
cy.get(':nth-child(2) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(2) > .panel-heading > .panel-title > .accordion-toggle').click()
cy.get('[name="question_type_1_0_1"]').select("Text Input")
cy.get(':nth-child(2) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(2) > .panel-body > :nth-child(4) > .col-sm-12 > .form-group > .ng-pristine > [ng-show="$ctrl.ready"] > .ql-container > .ql-editor').clear().type("Clue text - This is about Mathematics")
cy.get('[name="answer_phrase_1_0_1"]').clear().type("What is 4 * 2?")
cy.get('[name="answer_1_0_1_0"]').click({force: true}).clear().type("8")
cy.get('[name="answer_1_0_1_1"]').click({force: true}).clear().type("Eight")
cy.wait(10000)
cy.get('[name="match_type_1_1"]').select("Exact")
cy.get('[name="response_correct_1_0_1"]').type("Good, the answer is correct")
cy.get('[name="response_incorrect_1_0_1"]').type("Oops You're wrong")
//category2 for double jeopardy
cy.get(':nth-child(2) > .panel-body.ng-scope > .category-tabs > .nav > :nth-child(2) > .nav-link > .ng-binding').click()
cy.get('[name="category_name_1_1"]').clear().type("Category 2 for Double Jeopardy")
cy.get(':nth-child(2) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(1) > .panel-heading > .panel-title > .accordion-toggle > .ng-binding').click()
cy.get(':nth-child(2) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(1) > .panel-body > :nth-child(4) > .col-sm-12 > .form-group > .ng-pristine > [ng-show="$ctrl.ready"] > .ql-container > .ql-editor > p').clear().type("This category is about maths")
cy.get('[name="answer_phrase_1_1_0"]').clear().type("What is 6 * 5 ?")
cy.get('[name="answer_1_1_0_0"]').click({force: true}).clear().type("40")
cy.get('[name="answer_1_1_0_1"]').click({force: true}).clear().type("30")
cy.get(':nth-child(2) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(1) > .panel-body > .table-responsive > .table > .ng-isolate-scope > :nth-child(1) > .text-center > .ng-pristine').click()
cy.get(':nth-child(2) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(1) > .panel-body > .table-responsive > .table > .ng-isolate-scope > :nth-child(2) > .text-center > .ng-pristine').click()
cy.get('[name="response_correct_1_1_0"]').clear().type("Good")
cy.get('[name="response_incorrect_1_1_0"]').clear().type("OOPS Better luck next time")
//second question
cy.get(':nth-child(2) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(2) > .panel-heading > .panel-title > .accordion-toggle > .ng-binding').click()
cy.get('[name="question_type_1_1_1"]').select("Text Input")
cy.get(':nth-child(2) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane.active > .category-group > :nth-child(2) > :nth-child(2) > .panel-body > :nth-child(4) > .col-sm-12 > .form-group > .ng-pristine > [ng-show="$ctrl.ready"] > .ql-container > .ql-editor').clear().type("this part is about mathematics")
cy.get('[name="answer_phrase_1_1_1"]').type("what is 5*4?")
cy.get('[name="answer_1_1_1_0"]').click({force: true}).clear().type("20")
cy.get('[name="answer_1_1_1_1"]').click({force: true}).clear().type("Twenty")
//cy.get('[name="match_type_1_1"]').select("Exact")
cy.get('.tab-pane.active > .category-group > :nth-child(2) > :nth-child(2) > .panel-body > .table-responsive > .table > .ng-isolate-scope > :nth-child(2) > td.ng-scope > .form-control').select("Exact")
cy.get('[name="response_correct_1_1_1"]').type("Good")
cy.get('[name="response_incorrect_1_1_1"]').type("Better luck next time")
cy.get('a').contains('Final Jeopardy').click()
cy.get('[name="category_name_2_0"]').clear().type("Category 1 for final jeopardy")
cy.get(':nth-child(3) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane > .category-group > :nth-child(2) > .panel > .panel-heading > .panel-title > .accordion-toggle > .ng-binding').click()
cy.get(':nth-child(3) > .panel-body.ng-scope > .category-tabs > .tab-content > .tab-pane > .category-group > :nth-child(2) > .panel > .panel-body > :nth-child(4) > .col-sm-12 > .form-group > .ng-pristine > [ng-show="$ctrl.ready"] > .ql-container > .ql-editor > p').clear().type("This is about maths")
cy.get('[name="answer_phrase_2_0_0"]').clear().type("What is 10 *0 ?")
cy.get('[name="answer_2_0_0_0"]').clear().type("0")
cy.get('[name="answer_2_0_0_1"]').clear().type("10")
cy.get('.pull-right > .btn').click()
cy.wait(10000)
cy.get('.dropdown > .nav-link > .material-icons').click()
cy.get('.dropdown-menu > :nth-child(2) > .ng-scope').click()
cy.wait(1000)

   })
   //Edit the game
   it("Edit Jeopardy Game", function(){
    cy.viewport(1280, 720)
    cy.get('.panel-title.ng-binding').contains(" Sign In").should('be.visible')
    //    / cy.login('')
        cy.get('[placeholder="Email Address"]').type('saraswathi@elblearning.com')
        cy.get('[placeholder="Password"]').type('P@ssw0rd')
        cy.get('[type="submit"]').click()
        cy.wait(10000) 
        cy.get('[st-search="game_type"]').select("Jeopardy!")
        cy.wait(1000)
        cy.get('.filter > :nth-child(1) > .form-control').click({force:true}).type("Divya")
cy.wait(1000)
cy.get('tr.ng-scope > :nth-child(1) > .ng-binding').contains("Regression Jeopardy Game Divya").click()
cy.wait(1000)
cy.get('[translate="common.edit_game"]').click()
cy.wait(1000)
cy.get('[heading="Questions"]').click()
cy.wait(1000)
cy.get('.panel.panel-primary.ng-scope:nth-child(1)>*>*>a').click()
cy.wait(1000)
cy.get(':nth-child(1) > .panel-body.ng-scope > [ng-if="g_index < 2"] > :nth-child(3) > .form-control').select('Clue Text')
cy.wait(1000)
cy.get('a').contains('Double Jeopardy!').click({force:true})
cy.wait(1000)
cy.get(':nth-child(2) > .panel-body.ng-scope > [ng-if="g_index < 2"] > :nth-child(3) > .form-control').select("The question is about Mathema…")
cy.wait(1000)
cy.get('.interstitial-control.ng-scope > .form-control').select("This category is about maths")
cy.get('[ng-click="actions.verifyQuestionGroups()"]').click()
cy.wait(10000)
cy.get('.dropdown > .nav-link > .material-icons').click()
cy.get('.dropdown-menu > :nth-child(2) > .ng-scope').click()
cy.wait(1000)
})
   it.only("Play Game" ,function() {
    cy.viewport(1024,768)
cy.visit("https://tga-qa.staging.thetrainingarcade.com/games/jeopardy_new/regression-jeopardy-game-divya")
cy.wait(10000)
cy.get('button').contains('Start').click({scrollBehavior:false})
cy.wait(1000)
cy.get('div').contains("Info Popup").should('be.visible')
cy.wait(1000)
cy.get('button').contains('OK').click({scrollBehavior:false})
cy.wait(1000)
cy.get('[name="first_name"]').type("Divya")
cy.get('[name="last_name"]').type("Automation")
cy.get('[name="email"]').type("divya@elblearning.com")
cy.get('[name="employee_id"]').type("1")
cy.get('button').contains('Submit').click({scrollBehavior:false})
cy.wait(20000)
cy.get('div').contains('Category1 Jeopardy').should('be.visible')
cy.get('div').contains('Category 2 Jeopardy').should('be.visible')
cy.get('#question-266440 > * >*').contains("$200").should('be.visible')
cy.get('#question-266441 > * >*').contains("$400").should('be.visible')
cy.get('#question-266442 > * >*').contains("$200").should('be.visible')
cy.get('#question-266443 > * >*').contains("$400").should('be.visible')
cy.get('#question-266440 > * >*').contains("$200").click()
cy.wait(1000)
cy.get('.slider').type('300')
cy.wait(1000)
cy.get('button').contains('Submit').click()
cy.get('p').contains('Clue Text').should('be.visible')
//cy.pause()
cy.wait(10000)
//cy.get('div').contains('What is Java...?')
cy.get('div').contains('The Incorrect Answer')
cy.get('div').contains('A language')
cy.get('div').contains('Category1 Jeopardy')
cy.get('span').contains('For $300')
cy.get('div').contains('A language').click()
cy.wait(1000)
cy.get('div').contains('Correct').should('be.visible')
cy.get('div').contains('Correct feedback text').should('be.visible')
cy.get('button').contains('Next').click()
cy.wait(1000)
cy.get('div').contains('$300').should('be.visible')
cy.get('.1qu2vv32').click()
cy.get('div').contains('Menu').should('be.visible')
cy.get('button').contains('Resume').should('be.visible')
cy.get('button').contains('Sound ON').should('be.visible')
cy.get('button').contains('Restart Game').should('be.visible')
cy.get('button').contains('Privacy Policy').should('be.visible')
cy.get('button').contains('Legal').should('be.visible')
cy.get('button').contains('Log Out').should('be.visible')
cy.get('button').contains('Resume').should('be.visible').click()
cy.wait(1000)
cy.get('span').contains('$300').should('be.visible')
//entering incorrect answer and checking for the score negative
cy.get('#question-266441 > * >*').contains("$400").should('be.visible').click()
cy.get('p').contains('Java Program').should('be.visible')
cy.wait(5000)
cy.get('p').contains('Java Program').should('be.visible')
cy.wait(1000)
cy.get('div').contains('Category1 Jeopardy').should('be.visible')
cy.get('span').contains('For $400').should('be.visible')
cy.get('div').contains('Number of primitive datatypes in...?').should('be.visible')
cy.get('div').contains('8').should('be.visible')
cy.get('div').contains('6').should('be.visible')
cy.get('div').contains('6').should('be.visible').click()
cy.wait(1000)
cy.get('div').contains('Sorry...').should('be.visible')
cy.get('div').contains('Better luck next time').should('be.visible')
cy.get('button').contains('Next').should('be.visible').click()
cy.wait(1000)
cy.get('span').contains('-$100').should('be.visible')
cy.get('#question-266442 > * >*').contains("$200").should('be.visible').click()
cy.wait(5000)
cy.get('div').contains('Which of the following comes und...?').should('be.visible')
cy.get('div').contains('Inheritance').should('be.visible')
cy.get('div').contains('Incorrect').should('be.visible')
cy.get('span').contains('For $200').should('be.visible')
cy.get('div').contains('Incorrect').should('be.visible').click()
cy.get('div').contains("OOPS You're Wrong").should('be.visible')
cy.get('div').contains('Sorry...').should('be.visible')
cy.get('button').contains('Next').should('be.visible').click()
cy.wait(1000)
cy.get('span').contains('-$300').should('be.visible')
cy.get('#question-266443 > * >*').contains("$400").should('be.visible').click()
cy.get('p').contains('Java Program').should('be.visible')
cy.wait(1000)
cy.get('p').contains('Java Program').should('be.visible')
//giving correct answer for checking score
cy.wait(5000)
cy.get('div').contains('Number of primitive datatypes in...?').should('be.visible')
cy.get('div').contains('8').should('be.visible')
cy.get('div').contains('6').should('be.visible')
cy.get('div').contains('8').should('be.visible').click()
cy.wait(1000)
cy.get('div').contains('Correct').should('be.visible')
cy.get('div').contains("Wow you're good").should('be.visible')
cy.get('button').contains('Next').should('be.visible').click()
cy.wait(10000)
cy.get('span').contains('$100').should('be.visible')
cy.get('div').contains("Category 1 for Double Jeopardy").should('be.visible')
cy.get('div').contains("Category 2 for Double Jeopardy").should('be.visible')
cy.get('#question-266444 > button > span').contains("$400").should('be.visible')
cy.get('#question-266445 > button > span').contains("$800").should('be.visible')
cy.get('#question-266446 > button > span').contains("$400").should('be.visible')
cy.get('#question-266447 > button > span').contains("$800").should('be.visible')
cy.get('#question-266444 > button > span').contains("$400").should('be.visible').click()
cy.wait(1000)
cy.get('.slider').type('400')
cy.get('*').contains('Submit').click()
cy.wait(1000)
//going to answer the question correctly and check for score
cy.get('p').contains('The question is about Mathematics').should('be.visible')
cy.wait(1000)
cy.get('p').contains('The question is about Mathematics').should('be.visible')
//giving correct answer for checking score
cy.wait(1000)
cy.get('div').contains('What is 4 * 2?...?').should('be.visible')
cy.wait(1000)
cy.get('div').contains('8').should('be.visible')
cy.get('div').contains('10').should('be.visible')
cy.get('div').contains('12').should('be.visible')
cy.get('div').contains('8').should('be.visible').click()
cy.wait(1000)
cy.get('div').contains('Correct').should('be.visible')
//divya update after updating the create game script
//cy.get('div').contains("Wow you're good").should('be.visible')
cy.get('button').contains('Next').should('be.visible').click()
cy.wait(10000)
cy.get('span').contains('$500').should('be.visible')
//800 question category1
//Type Text Here
//Clue text - This is about Mathematics
cy.get('#question-266445 > button > span').contains("$800").should('be.visible').click()
cy.get('p').contains('Clue text - This is about Mathematics').should('be.visible')
cy.wait(1000)
cy.get('p').contains('Clue text - This is about Mathematics').should('be.visible')
cy.wait(1000)
//giving correct answer for checking score
cy.get('div').contains('What is 4 * 2?...?').should('be.visible')
cy.get('textarea').type('Eight')
cy.wait(1000)
cy.get('div').contains('Correct').should('be.visible')

//divya update after updating the create game script
//cy.get('div').contains("Wow you're good").should('be.visible')
cy.get('button').contains('Next').should('be.visible').click()
cy.wait(10000)
cy.get('span').contains('$500').should('be.visible')

})
})
